### ISSUE TITLE
What is the 'sontag_solver' binary?

### ISSUE THREAD

**Issue by ljmartin** [Hoecker-Lab/pocketoptimizer#12]
Hi all,
This software looks fantastic, and I'm looking forward to using it for test purposes (but haven't due to the HTMD licence). 

I couldn't find any information from the reference on the development of the sontag_solver binary. Looked through the paper and David Sontag's website but couldn't figure it out. Is it made in-house?

Could you please point me to the source?
Thanks!

**Comment by ljmartin** [comment]
OK maybe answering my own question, but I found this based on the text in the license: https://people.csail.mit.edu/dsontag/code/ - is that right?

**Comment by jnoske** [comment]
Yes this is correct, the corresponding reference can be found here: https://people.csail.mit.edu/dsontag/papers/sontag_uai08.pdf

**Comment by ljmartin** [comment]
thanks mate
