### ISSUE TITLE
High computational complexity for pocket screen

### ISSUE THREAD

**Issue by LDornfeld** [Hoecker-Lab/pocketoptimizer#2]
Dear Hoecker-Lab team,

Thank you for providing the pocketoptimizer on GitHub and its excellent documentation.

I am currently trying to implement the pocketoptimizer as a standard tool for pocket optimization procedures in our lab. However, in our design problems, we often have little knowledge about the contributions of residues in the binding pocket to the binding, which means we would like to screen all possible amino acid mutations in the binding pocket.

Currently, the pocketoptimizer generates all combinations of mutations and then calculates the energy of the rotamers. However, this approach is not feasible when optimizing a binding pocket with five contributing residues, resulting in 20⁵ possible combinations of mutations.

Therefore, I am interested in learning how your lab optimizes binding pockets. My idea is to first conduct an ALA-scan to identify important residues and then mutate them to all other amino acids alone or in pairs. I would appreciate your comments and suggestions.

Thank you once again for your fantastic work!

Cheers!

**Comment by jnoske** [comment]
Dear LDornfeld,

this is indeed a problem, PocketOptimizer can only limit the combinatorial optimization problem by pre-filtering the rotamers and ligand poses according to their vdW energy. However, as the number of design positions and residues allowed at these positions increases, the problem can no longer be solved deterministically. A suboptimal solution would be to use a smaller vdW filter threshold at the risk of losing more designs. The alanine scan idea sounds good and could potentially help create a more targeted design approach.  Another idea would be to not always include all design positions/residues in each design, but to do so in batches and work your way through iteratively. But again, you may lose certain combinations. I suppose there is no optimal solution to this problem.

Best,
Jakob

**Comment by LDornfeld** [comment]
Dear Jakob, 

thanks for your answer. Actually I ended up using the batch idea. It seems to pretty well reflect the experimental results we already got for the tested protein. To be fair, one also has a limited number of possible combinations for experimental strategies. So it stills is super useful for us 🙂 

Thanks again. 
Best,
Lars
