### ISSUE TITLE
conda environment installation failed

### ISSUE THREAD

**Issue by zaixizhang** [Hoecker-Lab/pocketoptimizer#4]
Hi,

Thanks for the brilliant work!
When I tried to install the conda environment with: conda env create -f environment.yml
it always reports solving environment failure, could you give some advice on building the environment?

Bests,

**Comment by jnoske** [comment]
Hi zaixizhang,

You can try to use the minimal environment:

conda env create -f simple_env.yml

Best,
Jakob
