### ISSUE TITLE
does the code requires linux to build the environment?

### ISSUE THREAD

**Issue by hima111997** [Hoecker-Lab/pocketoptimizer#5]
Hi, thanks for this nice code and rework.

Does the code require Linux to build the environment? Because both files generated ResolvePackageNotFound: errors

Thanks

**Comment by hima111997** [comment]
I tried the environment.yml on ubuntu 20.04 but it says: found conflicts.  Should i remove the packages version from the file?

**Comment by hima111997** [comment]
i tried removing the packages versions but it stopped without any error. the same happened with the simple_env file

![image](https://github.com/Hoecker-Lab/pocketoptimizer/assets/55895327/49a6e828-bccb-468a-888d-65760aeca993)

**Comment by jnoske** [comment]
Dear hima111997,

Yes the code requires linux and the environment should be fine under Ubuntu 20.04. For me it works under Ubuntu 20.04 with the simple_eny.yml. Maybe there is something wrong with your conda installation, since it stops without doing anything? It looks like you are already inside an environment (ffpenv).

**Comment by hima111997** [comment]
i tried it again using the simple_env.yml file after I deactivated the ffpenv environment but the same problem happened.

![image](https://github.com/Hoecker-Lab/pocketoptimizer/assets/55895327/e6954b5f-a11c-45d6-b0a9-709c49b543c1)

**Comment by jnoske** [comment]
I updated the conda environment files could you try it again with both files.

**Comment by hima111997** [comment]
the same problem happened but now it shows Solving environment: / Killed. when I searched for this, I found that the problem is that the command uses all the RAM (16 GB in my case) so it is killed. so I think the problem is either with the conda env command or my PC RAM.

**Comment by hima111997** [comment]
i think the problem is with the number of channels added in the environment file (https://github.com/conda/conda/issues/8650)

**Comment by jnoske** [comment]
Yes, I added more channels. But this should not be the issue, although I have 32 GB of RAM. Nonetheless you can see the packages required in the simple_env.yml file, so feel free to set up the environment yourself if this works for you.

**Comment by hima111997** [comment]
i tried in on another computer with Ubuntu 20.04 as the main OS. The simple_env file took more than two hours in performing the step of "solving environment" and did not finish so I stopped it. Does it usually take this long?

**Comment by jnoske** [comment]
Yes it can take that long, I would recommend you using the mamba solver: https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community.

**Comment by hima111997** [comment]
after i download mamba solver, should i use this command: conda env create -f simple_env.yml without any modifications?

**Comment by hima111997** [comment]
thank you for your help. it works now using the mamba solver with this command conda env create -f simple_env.yml
