### ISSUE TITLE
some questions related to different steps

### ISSUE THREAD

**Issue by hima111997** [Hoecker-Lab/pocketoptimizer#6]
Hi
i have followed the steps in the tutorial notebook and I have some questions:

1- in this code, is it possible to use other force fields (newer versions of Amber or charmm36 or different types for example OPLS)
for example, if I downloaded the force field from the corresponding website can I add it in a certain location in the code so that it can be used while optimizing?

```
 design = po.DesignPipeline(work_dir=project_dir,         # Path to working directory containing scaffold and ligand subdirectory
                           ph=7,                         # pH used for protein and ligand protonation
                           forcefield='charmm36',    # forcefield used for all energy computations (Use Amber as it is better tested!)
                           ncpus=8)                      # Number of CPUs for multiprocessing
```

2- in the step of parameterizing the ligand, if, for example, I generated the parameters using a newer version of CGenFF, can I add the generated files after performing this step (in ligand/charmm36/params) ?

```
# Prepare ligand
design.parameterize_ligand(input_ligand='ligand/IAA.sdf',  # Input ligand structure file could be .mol2/.sdf
                           addHs=True                      # Whether to add hydrogen atoms to the input structure
                           )
```

3-  in the step of generating ligand conformers, can I generate the conformers using different method (a deep learning method for example), align them, then combine them in one pdb file and use them while optimizing? 
```
design.prepare_lig_conformers(
    nconfs=50,         # Maximum number of conformers to produce (Sometimes these methods produce lower number of conformations)
    method='genetic',  # Genetic method in OpenBabel, other option is confab
    score='rmsd',      # Filters conformers based on RMSD
    )
```

4- while performing sample_sidechain_rotamers, sample_lig_poses, calculate_energies, or design it works but says: Error displaying widget. 
is there some widget I need to install?

![image](https://github.com/Hoecker-Lab/pocketoptimizer/assets/55895327/705b91c1-7946-47ad-b286-7f27ae5c6b58)

5- if the final generated files were not good can I return to the ligand grid and modify it then run sample_lig_poses --> calculate_energies --> design without deleting any files?

thanks

**Comment by jnoske** [comment]
Hi,

1) This is unfortunately not possible, since it would require many changes in the code.

2) Yes in theory it should be possible to place these parameters in the folder that you mentioned, as long as they are named correctly it should work. However, the atom names must match between the ligand.mol2 and the parameter files.

3) Yes this should be also possible if they are placed in ligand/FORCE_FIELD/conformers as ligand_confs.pdb. But again atom order and names must match those of the ligand.mol2 that has been prepared prior to that.

4) Regarding the widgets you may need to reinstall ipywidgets, however the only thing being displayed are progress bars, so for the function it is not critical.

5) If you modify the ligand grid you need to start a new design run by cleaning first and then start all over again. Otherwise delete the folder poses in ligand/FORCE_FIELD and the folder energies to calculate again from there. If it can not find the files it will create them again.

**Comment by hima111997** [comment]
Thank you for your answers. 
Regarding point number 1, you said it is not possible. Just to be sure that i understood your answer correctly, if there is a newer version of charmm36 ff can I download it and use it?

**Comment by jnoske** [comment]
We use htmd: https://github.com/Acellera/htmd so the force field must be implemented there, also many of the atom names are hard coded so you may encounter errors. Therefor, I would not recommend you change the force field.

**Comment by hima111997** [comment]
i checked this HTMD link (https://software.acellera.com/htmd/tutorials/system-building-protein-ligand.html) and found that when I use this command 
`charmm.listFiles()`

it produces 

```
---- Parameters files list: /home/ibrahim/miniconda3/envs/pocketoptimizer/lib/python3.10/site-packages/htmd/share/builder/charmmfiles/par/ ----
/par/par_all22_prot.prm
/par/par_all22star_prot.prm
/par/par_all35_ethers.prm
/par/par_all36_carb.prm
/par/par_all36_cgenff.prm
/par/par_all36_lipid.prm
/par/par_all36_na.prm
/par/par_all36_prot.prm
/par/par_all36m_prot.prm
/par/par_water_ions.prm
```

and it contains the file for the CHARMM36m
`/par/par_all36m_prot.prm`

also there is this command 
`charmm.defaultParam()`

which produces this list:
`['par/par_all36m_prot.prm', 'par/par_all36_lipid.prm', 'par/par_water_ions.prm', 'par/par_all36_cgenff.prm']`

and it contains the charmm36m parameters. 
so does this mean that if there is a newer version of CHARMM36 forcefield, can i download it, remove this file ('par/par_all36m_prot.prm',) from the list then add the new FF files to the list so that pocketoptimizer can use it?

**Comment by jnoske** [comment]
Hi,

In pocketoptimizer charmm.defaultParam() is used, so it will automatically use the charmm36m parameter set.

**Comment by hima111997** [comment]
So if there is a new version of charmm FF, can I download it and add it in HTMD and try to modify the defaulfparam() method to return the new file so that pocketoptimizer use it?

**Comment by jnoske** [comment]
I would not recommend you doing that, as it would probably cause many errors.

**Comment by hima111997** [comment]
okay thanks and sorry for asking too many questions
