### ISSUE TITLE
Question regarding the system 

### ISSUE THREAD

**Issue by Caihanfeng1703** [Hoecker-Lab/pocketoptimizer#8]
Hello, I would like to know if the pocketoprimizer can be operated in Windows environment. 

When I was trying to create an environment via Conda, there were lots of packages of errors. Do you have any comments or suggestions?

Best,
Hanfeng

**Comment by jnoske** [comment]
Unfortunately many of the packages pocketoptimizer is based on are only available for linux, so pocketoptimizer does not work on windows or mac.
