### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Caihanfeng1703** [Hoecker-Lab/pocketoptimizer#9]
When I enter the code of this part 

import sys             # Append the PocketOptimizer Code
sys.path.append('YOUR_POCKETOPTIMIZER_PATH')

import pocketoptimizer as po            # Import the pocketoptimizer module

design = po.DesignPipeline(work_dir=project_dir,      # Initialize a new design pipeline   # Path to working directory containing scaffold and ligand subdirectory
                           ph=7,                         # pH used for protein and ligand protonation
                           forcefield='amber_ff14SB',    # forcefield used for all energy computations (Use Amber as it is better tested!)
                           ncpus=8)                      # Number of CPUs for multiprocessing

**It appears that AttributeError: module "pocketoptimizer' has no attribute 'DesignPipeline', what could be the reason?**

**Comment by jnoske** [comment]
This should work. Can you make sure that the import of the pocketoptimizer module works correct. So that you are importing the the path which contains the pocketoptimizer subfolder?

**Comment by Caihanfeng1703** [comment]
Thank you, I found that the problem is i didn't set the correct path
